
DROP TABLE IF EXISTS media_person CASCADE;
DROP TABLE IF EXISTS media CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS city CASCADE;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS continent CASCADE;

DROP SEQUENCE IF EXISTS media_id_seq;
DROP SEQUENCE IF EXISTS person_id_seq;
DROP SEQUENCE IF EXISTS city_id_seq;
DROP SEQUENCE IF EXISTS country_id_seq;
DROP SEQUENCE IF EXISTS continent_id_seq;
